### ISSUE TITLE
Minimum CiviCRM issue on the enable page

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_civicrm#19]
I was using the project installer to install a few modules, and I'm running into a strange issue where `webform_civicrm` shows up as follows:

<img width="906" alt="screen shot 2017-09-07 at 11 47 35 am" src="https://user-images.githubusercontent.com/871421/30174984-8e089e2c-93c2-11e7-9c00-6dc30326780c.png">

This is especially strange because I've already enabled `webform_civicrm`. The version of `civicrm` is as follows:

<img width="506" alt="screen shot 2017-09-07 at 11 47 52 am" src="https://user-images.githubusercontent.com/871421/30175043-cc4808e4-93c2-11e7-916f-4f1dc71e444f.png">

I'm guessing the `1.x-` at the beginning of the version number is causing the problem?

**Comment by laryn** [comment]
PR to solve this by removing the version requirement -- no version prior to 4.7 works with Backdrop CMS anyway.

**Comment by jackaponte** [comment]
Weird--thanks for the heads up @laryn, I'll look into this and review your PR soon!

**Comment by herbdool** [comment]
@laryn @jackaponte had already fixed it in the .install but I guess we missed it being specified in .info too. I tried adding it as `dependencies[] = civicrm (>=1.x-4.7.0)` which should work according to the Drupal docs at least (https://www.drupal.org/docs/7/creating-custom-modules/writing-module-info-files-drupal-7x) but no luck. So probably can't hurt just to remove it for now.

**Comment by jackaponte** [comment]
Thanks again for reporting the problem, @laryn, and thanks @herbdool for merging the pull request! I tried last night to get the CiviCRM version number in .info to work properly to no avail; was going to keep banging on it, but you're right Herb, may as well make the module more functional right away, since minimum Civi version is currently an academic question for Webform CiviCRM in Backdrop!
